### PR TITLE
Link sef-logo in header to SEF homepage

### LINKED ISSUE #42: Link to the SEF site in the header won’t work
**Describe the bug**
- When you click on the SEF logo in the header you are supposed to go to the SEF site but there's a small bug.

**To Reproduce**
1. Go to https://sefglobal.org/academix/
2. Click on SEF logo
3. See error

**Expected behavior**
- Link it to the SEF site

**Are you working on this issue?**
Yes

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #42 

## Goals

- Link the SEF logo to the SEF site

## Approach

- Use `<a>` instead of `<Link>` component

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: app/src/components/App/index.tsx [hunk 1]
```diff
@@ -32,9 +27,9 @@ class App extends React.Component<AppProps> {
         <Layout style={{ background: '#fff' }}>
           <Header className={styles.header}>
             <div className={styles.logo}>
-              <Link to="https://sefglobal.org/">
+              <a href="https://sefglobal.org/">
```
Comment (jayasanka-sack) [inline app/src/components/App/index.tsx:30]: This should be work with local setups as well. If we redirect to sefglobal.org it's hard to work on a local environment.

This should be 
`<Link to="/academix">`
